export const SERVER_EVENTS = {
  CONNECTION: 'connection',
  DISCONNECT: 'disconnect',
  ERROR: 'error',
  MESSAGE: 'message',
} as const;

export const REDIS_CHANNELS = {
  GLOBAL_CHAT: 'global_chat',
  PRIVATE_CHAT: 'private_chat',
  SYSTEM_BROADCAST: 'system_broadcast',
  USER_STATUS: 'user_status',
} as const;

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500,
} as const;

export const ERROR_CODES = {
  INVALID_TOKEN: 'INVALID_TOKEN',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  CONNECTION_LIMIT_EXCEEDED: 'CONNECTION_LIMIT_EXCEEDED',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  INVALID_MESSAGE_FORMAT: 'INVALID_MESSAGE_FORMAT',
  DATABASE_ERROR: 'DATABASE_ERROR',
  ENCRYPTION_ERROR: 'ENCRYPTION_ERROR',
} as const;

export const DEFAULT_CONFIG = {
  JWT_EXPIRES_IN: '24h',
  JWT_REFRESH_EXPIRES_IN: '7d',
  BCRYPT_ROUNDS: 12,
  AES_IV_LENGTH: 16,
  MAX_CONNECTIONS_PER_IP: 10,
  RATE_LIMIT_WINDOW_MS: 900000, // 15 minutes
  RATE_LIMIT_MAX_REQUESTS: 100,
  LOG_LEVEL: 'info',
} as const;

export const SERVICE_NAMES = {
  GATEWAY: 'gateway',
  LOGIN: 'login',
  LOGIC: 'logic',
} as const;

export const MESSAGE_PRIORITIES = {
  LOW: 1,
  NORMAL: 2,
  HIGH: 3,
  CRITICAL: 4,
} as const;